# Real Server Configuration File
# Be careful on level

spring:
  config:
    activate:
      on-profile: real

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always              # 항상 SQL 초기화
      continue-on-error: true   # SQL 초기화 중 오류가 발생해도 계속 실행

