# Real Server Configuration File
# Be careful on level

logging:
  level:
    root: warn
    com.picstory: info

spring:
  profiles:
    active: real
    include:
      - db
      - login

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always              # 항상 SQL 초기화
      continue-on-error: true   # SQL 초기화 중 오류가 발생해도 계속 실행

server:
  port: 80
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728